version: '3.6'

volumes:
    db:
        driver: local
    db_data:
services:
    db:
        image: mysql:5
        container_name: opencampground_db
        volumes:
          - ${PWD}/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
          - db_data:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: yes
            MYSQL_DATABASE: campground
            MYSQL_USER: test
            MYSQL_PASSWORD: secret
        ports:
            - "3306:3306"
    app:
        image: ghcr.io/sgraham3/opencampground
        container_name: opencampground
        ports:
            - "3000:3000"
        depends_on:
            - db
        environment:
            DB_USER: test
            DB_NAME: campground
            DB_PASSWORD: secret
            DB_HOST: db

        command: /app/script/server -d
