# MySQL (default setup).
#
# Install the MySQL driver:
#   gem install mysql2
# On MacOS X:
#   gem install mysql -- --include=/usr/local/lib
# On Windows:
#   gem install mysql
#       Choose the win32 build.
#       Install MySQL and put its /bin directory on your path.
#
# for sqlite3
# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
#
#
#
# sqlite3
#
#   adapter: sqlite3
#   pool: 5
#   timeout: 5000
#
#

development:
  database: demo_campground
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: test
  password: secret
  host: localhost
  socket: <%= ["/tmp/mysqld.sock",
               "/tmp/msql.sock",
               "/var/run/mysqld/mysqld.sock",
               "/var/run/mysqld/mysql.sock"].detect{|socket|
                 File.exist?(socket)
               } %>

# for training we will use the same db as development
training:
  database: demo_campground
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: test
  password: secret
  host: localhost
  socket: <%= ["/tmp/mysqld.sock",
               "/tmp/msql.sock",
               "/var/run/mysqld/mysqld.sock",
               "/var/run/mysqld/mysql.sock"].detect{|socket|
                 File.exist?(socket)
               } %>

# Warning: The database defined as 'test' will be erased and
# re-generated from your development database when you run 'rake'.
# Do not set this db to the same as development or production.
test:
  database: open_campground_test
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: test
  password: secret
  host: localhost
  socket: <%= ["/tmp/mysqld.sock",
               "/tmp/msql.sock",
               "/var/run/mysqld/mysqld.sock",
               "/var/run/mysqld/mysql.sock"].detect{|socket|
                 File.exist?(socket)
               } %>

production:
  database: campground
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: test
  password: secret
  host: localhost
  socket: <%= ["/tmp/mysqld.sock",
               "/tmp/msql.sock",
               "/var/run/mysqld/mysqld.sock",
               "/var/run/mysqld/mysql.sock"].detect{|socket|
                 File.exist?(socket)
               } %>
